export interface ProductVariant {
  weightGrams: number;
  weightLabel: string;
  price: number;
  inStock: boolean;
}

export type GrindOption = 'whole' | 'coarse' | 'medium' | 'fine';

export interface GrindOptionDetail {
  id: GrindOption;
  label: string;
  description: string;
  recommendedFor: string;
}

export const GRIND_OPTIONS: GrindOptionDetail[] = [
  {
    id: 'whole',
    label: 'Whole Beans',
    description: 'Biji utuh segar untuk digiling sendiri sebelum seduh.',
    recommendedFor: 'Maksimum freshness & grinder manual/otomatis',
  },
  {
    id: 'coarse',
    label: 'Coarse Grind',
    description: 'Gilingan kasar dengan partikel menyerupai sea salt kasar.',
    recommendedFor: 'French Press, Cold Brew, Cupping',
  },
  {
    id: 'medium',
    label: 'Medium Grind',
    description: 'Gilingan sedang sehalus pasir pantai bersih.',
    recommendedFor: 'V60, Kalita Wave, Aeropress, Clever Dripper',
  },
  {
    id: 'fine',
    label: 'Fine Grind',
    description: 'Gilingan halus bertekstur bubuk gula halus / tepung.',
    recommendedFor: 'Espresso Machine, Moka Pot, Tubruk Halus',
  },
];

export interface BrewRecipe {
  method: string;
  dose: string;
  water: string;
  ratio: string;
  temp: string;
  time: string;
  steps: string[];
}

export interface CoffeeProduct {
  id: string;
  slug: string;
  name: string;
  category: 'filter' | 'espresso' | 'reserve';
  categoryLabel: string;
  series: 'Ijen Series' | 'Sunda Series' | 'Java Exotic' | 'Grand Reserve' | 'Espresso Roast';
  origin: string;
  region: string;
  altitude: string;
  varietal: string;
  process: string;
  roastLevel: 'Light' | 'Light-Medium' | 'Medium' | 'Medium-Dark';
  tastingNotes: string[];
  flavorCategory: ('Fruity' | 'Floral' | 'Chocolaty' | 'Nutty' | 'Sweet')[];
  description: string;
  story: string;
  variants: ProductVariant[];
  basePrice: number;
  defaultWeight: string;
  imageUrl: string;
  badge?: string;
  acidity: number; // 1-5
  sweetness: number; // 1-5
  body: number; // 1-5
  brewingRecipe: BrewRecipe;
  isFreshCrop?: boolean;
  isFeatured?: boolean;
}

export const PRODUCTS: CoffeeProduct[] = [
  // --- FEATURED IG RELEASE: ARGOPURO WALIDA SERIES ---
  {
    id: 'argopuro-walida',
    slug: 'argopuro-walida-natural-anaerobic',
    name: 'Argopuro Walida Natural Anaerobic',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Gunung Argopuro, Probolinggo - Jember',
    altitude: '1,300 - 1,600 MASL',
    varietal: 'Kartika, Typica, USDA 762',
    process: 'Natural Anaerobic',
    roastLevel: 'Light',
    tastingNotes: ['Plum', 'Blood Orange', 'Dark Cherry', 'Juicy Body'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Rilisan baru Walida Series dari lereng Gunung Argopuro. Dominasi karakter buah plum matang berpadu kesegaran citrus blood orange dan aftertaste dark cherry yang sangat juicy.',
    story: 'Karya mikro-lot kelompok tani Walida di lereng Argopuro, Jawa Timur. Ceri merah pilihan diproses dengan fermentasi anaerobik 72 jam menghasilkan ester buah tropis yang begitu semerbak dan jernih.',
    basePrice: 68000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 68000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 128000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 335000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'New Release',
    acidity: 4,
    sweetness: 5,
    body: 4,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: [
        '00:00 - 00:40: Blooming 45g air, swirl lembut.',
        '00:40 - 01:15: Tuang pelan melingkar hingga 135g.',
        '01:15 - 02:00: Tuang akhir ke titik tengah hingga 225g.',
        '02:15: Sajikan di cangkir kaca untuk menangkap aroma blood orange.',
      ],
    },
  },

  // --- FILTER: IJEN SERIES ---
  {
    id: 'ijen-cm',
    slug: 'ijen-carbonic-maceration',
    name: 'Ijen Carbonic Maceration',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Gunung Ijen, Banyuwangi - Bondowoso',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika, USDA 762',
    process: 'Carbonic Maceration',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Peach', 'Jasmine', 'Rich Taste', 'Medium Body'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Fermentasi anaerobik bertekanan karbon dioksida terkontrol menghasilkan aroma floral melati yang intens dipadukan manisnya buah persik matang.',
    story: 'Dipanen dari lereng kaldera aktif Gunung Ijen oleh para petani binaan 52 Coffee. Biji ceri merah diproses dengan injeksi CO2 murni selama 72 jam untuk mengekstrak kompleksitas asam laktat alami dan kelembutan jasmine.',
    basePrice: 65000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 65000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 120000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 320000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Fresh Crop',
    acidity: 4,
    sweetness: 4,
    body: 3,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 15s',
      steps: [
        '00:00 - 00:40: Blooming 45g air, swirl lembut 5 detik.',
        '00:40 - 01:15: Tuang kedua hingga 135g dalam gerakan spiral konstan.',
        '01:15 - 02:00: Tuang ketiga hingga 225g secara memusat.',
        '02:15: Selesai, sajikan dan nikmati aroma floral jasmine yang merekah.',
      ],
    },
  },
  {
    id: 'ijen-lactic',
    slug: 'ijen-lactic',
    name: 'Ijen Lactic',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Kawah Ijen, Bondowoso',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika',
    process: 'Lactic Anaerobic Fermentation',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Mango', 'Lychee', 'Lime', 'Creamy', 'Chocolate'],
    flavorCategory: ['Fruity', 'Sweet', 'Chocolaty'],
    description: 'Sensasi rasa tropis mangga ranum dan leci berpadu keasaman segar jeruk nipis, diakhiri dengan tekstur creamy bagai cokelat susu.',
    story: 'Mengembangkan kultur bakteri asam laktat murni dalam bejana stainless steel tertutup untuk memecah musilase ceri secara lembut dan menghasilkan body creamy istimewa.',
    basePrice: 59000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 59000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 109000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 290000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 4,
    isFreshCrop: true,
    brewingRecipe: {
      method: 'Kalita Wave 155',
      dose: '14g',
      water: '220ml',
      ratio: '1:15.7',
      temp: '91°C',
      time: '2m 30s',
      steps: [
        '00:00 - 00:35: Blooming 40g air.',
        '00:35 - 01:10: Tuang pelan hingga 120g.',
        '01:10 - 02:00: Tuang akhir hingga 220g.',
        'Nikmati body creamy dan aftertaste lychee yang panjang.',
      ],
    },
  },
  {
    id: 'ijen-yellow-bourbon',
    slug: 'ijen-yellow-bourbon',
    name: 'Ijen Yellow Bourbon',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Lereng Gunung Ijen',
    altitude: '1,500 MASL',
    varietal: 'Yellow Bourbon',
    process: 'Honey Processed',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Honey', 'Almond', 'Smooth Body'],
    flavorCategory: ['Sweet', 'Nutty'],
    description: 'Karakteristik langka varietal Yellow Bourbon dengan sentuhan madu hutan liar, keharuman kacang almond panggang, serta tekstur lembut di lidah.',
    story: 'Varietas langka Yellow Bourbon yang berbuah kuning cerah ditanam secara terbatas di ketinggian 1.500 mdpl. Proses honey menjaga lapisan mucilage manis menempel saat penjemuran di raised beds.',
    basePrice: 59000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 59000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 109000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 290000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?q=80&w=800&auto=format&fit=crop',
    acidity: 3,
    sweetness: 4,
    body: 3,
    brewingRecipe: {
      method: 'Origami Dripper',
      dose: '15g',
      water: '240ml',
      ratio: '1:16',
      temp: '93°C',
      time: '2m 20s',
      steps: [
        'Blooming 45ml selama 40 detik.',
        'Continuous pour stabil sampai menyentuh 240ml di menit 01:45.',
        'Drawdown berakhir di menit 02:20.',
      ],
    },
  },

  // --- FILTER: SUNDA SERIES ---
  {
    id: 'sunda-puntang-honey',
    slug: 'puntang-honey',
    name: 'Puntang Honey',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Sunda Series',
    origin: 'West Java, Indonesia',
    region: 'Gunung Puntang, Bandung',
    altitude: '1,300 - 1,600 MASL',
    varietal: 'Typica, Sigarar Utang',
    process: 'Yellow Honey',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Honey', 'Peach', 'Chocolate-Like'],
    flavorCategory: ['Sweet', 'Fruity', 'Chocolaty'],
    description: 'Kemewahan terroir tanah Priangan Barat. Manis alami madu bunga, kelembutan buah persik, dan sentuhan aroma cokelat elegan.',
    story: 'Gunung Puntang memiliki warisan sejarah kopi Jawa legendaris. Dipetik di tingkat kematangan optimal brix 22% dan dijemur lambat di greenhouse terlindung matahari langsung.',
    basePrice: 95000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 95000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 179000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 379000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=800&auto=format&fit=crop',
    acidity: 3,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '16g',
      water: '250ml',
      ratio: '1:15.6',
      temp: '92°C',
      time: '2m 30s',
      steps: [
        'Blooming 50g selama 45 detik.',
        'Tuang 100g air ke bagian tengah secara berputar.',
        'Tuang sisa 100g air pada menit 01:20.',
      ],
    },
  },
  {
    id: 'sunda-puntang-natural',
    slug: 'puntang-natural',
    name: 'Puntang Natural',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Sunda Series',
    origin: 'West Java, Indonesia',
    region: 'Gunung Puntang, Bandung',
    altitude: '1,300 - 1,600 MASL',
    varietal: 'Typica',
    process: 'Dry Natural Process',
    roastLevel: 'Light',
    tastingNotes: ['Pineapple', 'Berry', 'Jackfruit'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Ledakan buah-buahan tropis Nusantara: nanas matang, sensasi buah berry liar, dan harum manis nangka yang semerbak.',
    story: 'Proses natural klasik dengan waktu pengeringan 28 hari penuh di atas meja jemur bambu. Menghasilkan karakter funk tropis yang sangat bersih dan menyenangkan.',
    basePrice: 99000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 99000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 185000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 399000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1524350876685-274059332603?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 3,
    isFeatured: true,
    brewingRecipe: {
      method: 'Aeropress (Inverted)',
      dose: '15g',
      water: '200ml',
      ratio: '1:13.3',
      temp: '89°C',
      time: '1m 45s',
      steps: [
        'Masukkan kopi gilingan medium-fine ke tabung terbalik.',
        'Tuang 200ml air 89°C, aduk 5 putaran perlahan.',
        'Tutup filter paper yang telah dibilas pada menit 01:00.',
        'Balikkan dan tekan lembut selama 30 detik.',
      ],
    },
  },

  // --- FILTER: JAVA EXOTIC SERIES (From 52 Coffee Official Lineup) ---
  {
    id: 'sumbing-supernova-wash',
    slug: 'sumbing-supernova-wash',
    name: 'Sumbing Supernova Wash',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Sumbing, Temanggung',
    altitude: '1,200 - 1,700 MASL',
    varietal: 'Kartika, Typica',
    process: 'Supernova Wash Process',
    roastLevel: 'Light',
    tastingNotes: ['Explosive Berry', 'Bright', 'Brown-Cane Sugar', 'Candy-Like'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Explosive Berry, Complex, & Candy-Like. Biji kopi istimewa dari lereng Gunung Sumbing dengan kecerahan rasa berry yang meledak dan manis tebu alami.',
    story: 'Diproses dengan teknik Supernova Wash presisi di Temanggung, Jawa Tengah. Menghadirkan kejernihan rasa tingkat kompetisi dengan aftertaste permen buah yang tahan lama.',
    basePrice: 139000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: '/images/java-exotic-lineup.jpg',
    badge: 'Java Exotic',
    acidity: 4,
    sweetness: 5,
    body: 3,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: [
        '00:00: Blooming 45g air 91°C selama 40 detik.',
        '00:40: Tuangan kedua spiral lembut hingga 135g.',
        '01:15: Tuangan akhir memusat hingga 225g.',
      ],
    },
  },
  {
    id: 'prau-black-honey-triple-yeast',
    slug: 'prau-black-honey-triple-yeast',
    name: 'Prau Black Honey Triple Yeast',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Prau, Temanggung',
    altitude: '1,400 - 1,750 MASL',
    varietal: 'Kartika',
    process: 'Black Honey Triple Yeast',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Brown Sugar', 'Peach', 'Blackcurrant', 'Tea-Like'],
    flavorCategory: ['Sweet', 'Fruity'],
    description: 'Brown Sugar, Peach, Blackcurrant, & Tea-Like. Perpaduan manisnya brown sugar dan aroma persik segar dengan kelembutan blackcurrant tea.',
    story: 'Fermentasi inokulasi tiga varian yeast terpilih pada pulpa ceri hitam Gunung Prau menghasilkan body manis berlapis dan aftertaste seperti seduhan teh hitam beraroma buah.',
    basePrice: 115000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 115000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 215000, inStock: true },
    ],
    imageUrl: '/images/java-exotic-lineup.jpg',
    badge: 'Triple Yeast',
    acidity: 3,
    sweetness: 5,
    body: 4,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'Kalita Wave / Flat Bottom',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 30s',
      steps: [
        'Blooming 50g selama 45 detik.',
        'Tuang perlahan konstan hingga 240ml.',
      ],
    },
  },
  {
    id: 'sindoro-lavender-candy-wash',
    slug: 'sindoro-lavender-candy-wash',
    name: 'Sindoro Lavender Candy Wash',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Sindoro, Temanggung',
    altitude: '1,500 - 1,800 MASL',
    varietal: 'Kartika',
    process: 'Washed Extended',
    roastLevel: 'Light',
    tastingNotes: ['Purple Flower', 'Floral', 'Clean', 'Plum Candy'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Purple Flower, Floral, Clean, Plum Candy. Aroma bunga lavender dan kelembutan permen plum ungu yang sangat bersih dan elegan.',
    story: 'Kurasi terroir lereng Gunung Sindoro dengan udara sejuk pegunungan. Menggunakan pencucian air pegunungan alami menghasilkan profil floral yang menakjubkan.',
    basePrice: 139000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: '/images/java-exotic-hero.jpg',
    badge: 'Floral Candy',
    acidity: 4,
    sweetness: 5,
    body: 3,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '90°C',
      time: '2m 10s',
      steps: [
        'Blooming 45g selama 35 detik.',
        'Tuang spiral hingga 140g.',
        'Tuang akhir memusat hingga 225g.',
      ],
    },
  },
  {
    id: 'prau-not-chiroso',
    slug: 'prau-not-chiroso-style',
    name: 'Prau Not-Chiroso Style',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Prau, Temanggung',
    altitude: '1,500 - 1,800 MASL',
    varietal: 'Kartika Exotic',
    process: 'Experimental Washed',
    roastLevel: 'Light',
    tastingNotes: ['Tropical', 'Floral', 'Pineapple-Jasmine'],
    flavorCategory: ['Fruity', 'Floral'],
    description: 'Tropical, Floral, & Pineapple-Jasmine. Terinspirasi profil varietas langka Chiroso dengan harum bunga melati dan manis nanas tropis.',
    story: 'Eksperimen proses mikro-lot dari lereng Gunung Prau dengan kontrol pH fermentasi untuk mengekstrak senyawa aromatik pinapple-jasmine yang segar.',
    basePrice: 139000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: '/images/java-exotic-lineup.jpg',
    badge: 'Experimental',
    acidity: 4,
    sweetness: 4,
    body: 3,
    isFreshCrop: true,
    isFeatured: false,
    brewingRecipe: {
      method: 'Origami Dripper',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: [
        'Blooming 45g selama 40 detik.',
        'Tuang bertahap hingga 225ml.',
      ],
    },
  },
  {
    id: 'prau-hybrid-wash',
    slug: 'prau-hybrid-wash-oxigenium',
    name: 'Prau Hybrid-Wash Oxigenium',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Prau, Temanggung',
    altitude: '1,400 - 1,700 MASL',
    varietal: 'Kartika',
    process: 'Hybrid-Wash Oxigenium',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Clean', 'Balanced', 'Subtle Floral'],
    flavorCategory: ['Floral', 'Sweet'],
    description: 'Clean, Balanced, & Subtle Floral. Profil cangkir yang jernih seimbang dengan sentuhan aroma bunga putih halus yang menenangkan.',
    story: 'Teknologi injeksi oksigen terkontrol pada fermentasi basah untuk menjaga kejernihan rasa dan kebersihan aftertaste.',
    basePrice: 115000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 115000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 215000, inStock: true },
    ],
    imageUrl: '/images/java-exotic-lineup.jpg',
    badge: 'Clean Cup',
    acidity: 3,
    sweetness: 4,
    body: 3,
    isFreshCrop: true,
    isFeatured: false,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 20s',
      steps: [
        'Blooming 45g selama 40 detik.',
        'Tuang 90g melingkar.',
        'Tuang 90g memusat.',
      ],
    },
  },

  // --- GRAND RESERVE MICRO-LOT SERIES (From 52 Coffee Official Lineup) ---
  {
    id: 'haraz-royal-origin',
    slug: 'haraz-royal-origin-yemen',
    name: 'Haraz Royal Origin Yemen',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Haraz Mountains, Yemen',
    region: 'Jabal Haraz High Valleys',
    altitude: '2,100 - 2,400 MASL',
    varietal: 'Udaini, Jaadi (Ancient Typica)',
    process: 'Raised Bed Sun Dried Natural',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Dried Fruits', 'Raisin', 'Exotic Spices', 'Cocoa Nibs'],
    flavorCategory: ['Fruity', 'Chocolaty', 'Sweet'],
    description: 'Kopi pusaka purba dari lembah terjal Yaman Haraz. Kepekatan aroma buah kering kismis berpadu rempah eksotis dan cokelat hitam bangsawan.',
    story: 'Ditanam di teras batu kuno ketinggian 2.400 mdpl di Yaman oleh keluarga petani generasi ke-7. Dikeringkan di atap rumah bertingkat di bawah sinar matahari gurun pegunungan yang kering.',
    basePrice: 390000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 390000, inStock: true },
    ],
    imageUrl: '/images/grand-reserve-series.jpg',
    badge: 'Royal Yemen',
    acidity: 3,
    sweetness: 5,
    body: 5,
    isFeatured: true,
    brewingRecipe: {
      method: 'Origami / Kono Dripper',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '93°C',
      time: '2m 40s',
      steps: [
        '00:00: Blooming 45g air panas 93°C selama 45 detik.',
        '00:45: Tuang kedua pelan memusat hingga 140g.',
        '01:30: Tuang akhir hingga 240g.',
      ],
    },
  },
  {
    id: 'el-vergel-magnum-sidra',
    slug: 'el-vergel-magnum-sidra-colombia',
    name: 'El-Vergel Magnum Sidra Colombia',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Tolima, Colombia',
    region: 'El Vergel Estate, Fresno',
    altitude: '1,900 - 2,100 MASL',
    varietal: 'Sidra (Bourbon x Typica Hybrid)',
    process: 'Anaerobic Natural Cold Fermentation',
    roastLevel: 'Light',
    tastingNotes: ['Strawberry Jam', 'Papaya', 'Sparkling Acidity', 'Jasmine'],
    flavorCategory: ['Fruity', 'Floral', 'Sweet'],
    description: 'Varietas legendaris Sidra dari perkebunan El Vergel, Kolombia. Keasaman buah tropis yang berdegup seperti sampanye berpadu selai stroberi dan aroma jasmine.',
    story: 'Kultivar Sidra langka dari juara kompetisi seduh dunia. Difermentasi dalam tangki pendingin terkontrol untuk mempertahankan asam malat dan keharuman floral yang sangat kaya.',
    basePrice: 390000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 390000, inStock: true },
    ],
    imageUrl: '/images/grand-reserve-series.jpg',
    badge: 'Competition Sidra',
    acidity: 5,
    sweetness: 5,
    body: 4,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '240ml',
      ratio: '1:16',
      temp: '90°C',
      time: '2m 15s',
      steps: [
        '00:00: Blooming 50g selama 40 detik.',
        '00:40: Continuous pour lembut hingga 240ml.',
      ],
    },
  },
  {
    id: 'inmaculada-pink-bourbon',
    slug: 'inmaculada-pink-bourbon',
    name: 'Inmaculada Pink Bourbon Colombia',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Valle del Cauca, Colombia',
    region: 'Finca Inmaculada, Pichindé',
    altitude: '1,750 - 2,000 MASL',
    varietal: 'Pink Bourbon',
    process: 'Natural Anaerobic',
    roastLevel: 'Light',
    tastingNotes: ['White Peach', 'Mandarin', 'Sweet Honey', 'Jasmine'],
    flavorCategory: ['Fruity', 'Floral', 'Sweet'],
    description: 'Pink Bourbon dari salah satu produsen kopi micro-lot paling bergengsi di dunia, Finca Inmaculada. Manis buah persik putih dan madu berpadu kesegaran mandarin orange.',
    story: 'Biji ceri merah muda dipetik pada puncak kemanisan brix 24% di perbukitan Andes Pichindé. Disangrai presisi di Malang untuk menonjolkan keanggunan alaminya.',
    basePrice: 380000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 380000, inStock: true },
    ],
    imageUrl: '/images/grand-reserve-series.jpg',
    badge: 'Micro-Lot',
    acidity: 4,
    sweetness: 5,
    body: 3,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 10s',
      steps: [
        '00:00: Blooming 45g selama 35 detik.',
        '00:35: Tuangan kedua hingga 135g.',
        '01:10: Tuangan ketiga hingga 225g.',
      ],
    },
  },
  {
    id: 'sumbing-supernova',
    slug: 'sumbing-supernova-wash',
    name: 'Sumbing Supernova Wash',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Lereng Gunung Sumbing',
    altitude: '1,600 - 1,900 MASL',
    varietal: 'Sigarar Utang',
    process: 'Supernova Washed (Extended Anaerobic Wash)',
    roastLevel: 'Light',
    tastingNotes: ['Explosive Berry', 'Complex', 'Candy-Like'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Kejernihan washed coffee dengan ledakan rasa permen berry ungu yang kompleks, crisp, dan menyegarkan.',
    story: 'Teknik Supernova mencuci ceri kopi di suhu air dingin 12°C selama 96 jam untuk menjaga kesegaran asam malat murni dan aroma candy-like.',
    basePrice: 139000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
    badge: 'Limited Run',
    acidity: 5,
    sweetness: 4,
    body: 3,
    brewingRecipe: {
      method: 'Hario Switch',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 45s',
      steps: [
        'Buka switch: Tuang 120ml air mengalir normal (00:00 - 00:45).',
        'Tutup switch: Tuang sisa 120ml air, rendam selama 1 menit.',
        '01:45: Buka switch untuk drawdown akhir.',
      ],
    },
  },
  {
    id: 'prau-natural-secret',
    slug: 'prau-natural-secret-project',
    name: 'Prau Natural Secret Project',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Plataran Gunung Prau, Wonosobo',
    altitude: '1,600 - 2,000 MASL',
    varietal: 'Kartika',
    process: 'Secret Fermentation Natural',
    roastLevel: 'Light',
    tastingNotes: ['Strawberry Candy', 'White Floral', 'Fruit Punch'],
    flavorCategory: ['Fruity', 'Floral', 'Sweet'],
    description: 'Proyek rahasia kolaborasi mikrolot tertinggi di Jawa Tengah. Dominasi rasa permen stroberi, bunga putih lily, dan jus buah fruit punch yang menggetarkan.',
    story: 'Ceri merah dipetik di ketinggian ekstrem 2.000 MASL di mana kabut dingin memperlambat pematangan buah. Diolah dengan metode fermentasi bertingkat yang dijaga kerahasiaannya.',
    basePrice: 139000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=800&auto=format&fit=crop',
    badge: 'Secret Series',
    acidity: 5,
    sweetness: 5,
    body: 3,
    isFreshCrop: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: [
        'Bloom 45g air, swirl pelan.',
        '00:40: Tuang melingkar hingga 135g.',
        '01:15: Tuang center pour hingga 225g.',
      ],
    },
  },

  // --- FILTER: GRAND RESERVE MICRO-LOT ---
  {
    id: 'reserve-magnum-sidra',
    slug: 'magnum-sidra-el-vergel-cauca',
    name: 'Magnum Sidra El Vergel Cauca',
    category: 'reserve',
    categoryLabel: 'Grand Reserve Micro-Lot',
    series: 'Grand Reserve',
    origin: 'Colombia',
    region: 'Cauca, Finca El Vergel',
    altitude: '1,850 - 2,000 MASL',
    varietal: 'Sidra (Bourbon x Typica heirloom)',
    process: 'Koji Anaerobic Natural',
    roastLevel: 'Light',
    tastingNotes: ['Tropical', 'Syrup', 'Layered Cocoa', 'Brown Sugar'],
    flavorCategory: ['Fruity', 'Sweet', 'Chocolaty'],
    description: 'Kopi kompetisi kelas dunia dari perkebunan El Vergel Cauca. Kompleksitas rasa tropis lebat dengan mouthfeel syrupy mewah dan cocoa manis.',
    story: 'Varietas Sidra langka yang disuntikkan spora Koji Jepang untuk memaksimalkan hidrolisis pati menjadi gula fruktosa murni. Menghasilkan profil rasa yang tak terlupakan bagi para kolektor specialty coffee.',
    basePrice: 72000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 72000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 180000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 350000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 685000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?q=80&w=800&auto=format&fit=crop',
    badge: 'Grand Reserve',
    acidity: 5,
    sweetness: 5,
    body: 4,
    isFeatured: true,
    brewingRecipe: {
      method: 'Competition V60 Recipe',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '93°C',
      time: '2m 10s',
      steps: [
        '00:00: 50g blooming air, bypass lembut.',
        '00:40: 70g circular pour.',
        '01:10: 60g center pour.',
        '01:40: 60g center pour finishing.',
      ],
    },
  },
  {
    id: 'reserve-el-triunfo-geisha',
    slug: 'el-triunfo-geisha-tolima',
    name: 'El Triunfo Geisha Tolima',
    category: 'reserve',
    categoryLabel: 'Grand Reserve Micro-Lot',
    series: 'Grand Reserve',
    origin: 'Colombia',
    region: 'Planadas, Tolima',
    altitude: '1,900 - 2,100 MASL',
    varietal: 'Geisha (Panama clone origin)',
    process: 'Washed Slow Dry',
    roastLevel: 'Light',
    tastingNotes: ['Jasmine', 'Bergamot', 'Peach', 'Tea-Like'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Puncak keanggunan kopi dunia. Geisha murni dengan aroma melati surgawi, keasaman bergamot earl grey, dan kelembutan teh persik.',
    story: 'Ditanam di ketinggian 2.100 mdpl di Tolima, dipetik hanya pada tingkat kematangan kristal gula tertinggi. Dikeringkan di bawah naungan terkontrol selama 35 hari.',
    basePrice: 86000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 86000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 200000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 380000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 709000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=800&auto=format&fit=crop',
    badge: 'Top Lot 01',
    acidity: 5,
    sweetness: 5,
    body: 2,
    isFeatured: true,
    brewingRecipe: {
      method: 'Orea V3 / V60',
      dose: '15g',
      water: '240ml',
      ratio: '1:16',
      temp: '90°C',
      time: '2m 00s',
      steps: [
        'Bloom 45g air selama 35 detik.',
        'Tuang 3x 65g dengan aliran air sangat lembut.',
        'Sajikan di suhu hangat untuk sensasi floral maksimal.',
      ],
    },
  },
  {
    id: 'reserve-yemen-haraz',
    slug: 'yemen-haraz-golden-harvest',
    name: 'Yemen Haraz Golden Harvest',
    category: 'reserve',
    categoryLabel: 'Grand Reserve Micro-Lot',
    series: 'Grand Reserve',
    origin: 'Yemen',
    region: 'Haraz Mountains',
    altitude: '2,200 - 2,400 MASL',
    varietal: 'Jaadi, Dawairi (Ancient Landrace)',
    process: 'Anaerobic Natural Terraces',
    roastLevel: 'Light',
    tastingNotes: ['Sweet Jammy Strawberry', 'Vanilla'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Keajaiban kopi kuno dari tebing terjal pegunungan Haraz Yaman. Rasa selai stroberi yang pekat dengan sentuhan rempah vanili mistis.',
    story: 'Pohon kopi tua berusia ratusan tahun tumbuh di terasering bebatuan terjal Yaman. Diproses secara tradisi purba berpadu teknik fermentasi anaerobik modern.',
    basePrice: 59000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 59000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 165000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 229000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 549000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?q=80&w=800&auto=format&fit=crop',
    badge: 'Ancient Lot',
    acidity: 4,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 20s',
      steps: [
        'Bloom 50g selama 40 detik.',
        'Continuous pour 190ml air memutar pelan.',
      ],
    },
  },

  // --- ESPRESSO BASED ROAST PROFILES ---
  {
    id: 'espresso-dampit',
    slug: 'dampit-natural-robusta',
    name: 'Dampit Natural (Fine Robusta)',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Espresso Roast',
    origin: 'East Java, Indonesia',
    region: 'Dampit, Kabupaten Malang',
    altitude: '800 - 1,000 MASL',
    varietal: 'Fine Robusta Klon Tugusari',
    process: 'Natural Process',
    roastLevel: 'Medium-Dark',
    tastingNotes: ['Chocolate', 'Brown Sugar', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Sweet', 'Nutty'],
    description: 'Robusta kebanggaan Malang Selatan. Karakter cokelat pekat tanpa rasa getir kasar, manisnya gula aren, dan crema tebal yang mantap.',
    story: 'Berasal dari kebun rakyat di perbukitan Dampit Malang Selatan yang tersohor. Disortir dengan teliti hingga zero defect untuk menghasilkan kopi susu kekinian yang berkarakter kuat.',
    basePrice: 35000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 35000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 85000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg (Hopper Size)', price: 150000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Malang Origin',
    acidity: 1,
    sweetness: 4,
    body: 5,
    brewingRecipe: {
      method: 'Espresso / Es Kopi Susu',
      dose: '18g',
      water: '36g liquid (1:2 ratio)',
      ratio: '1:2',
      temp: '93°C',
      time: '25 - 28 detik',
      steps: [
        'Dosing 18g di basket portafilter 58mm.',
        'WDT tool & tamping rata 15kg.',
        'Ekstraksi 36ml dalam waktu 27 detik.',
        'Campur dengan 120ml fresh milk dingin dan 20ml aren cair.',
      ],
    },
  },
  {
    id: 'espresso-kintamani',
    slug: 'kintamani-full-wash-arabica',
    name: 'Kintamani Full Wash (Arabica)',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Espresso Roast',
    origin: 'Bali, Indonesia',
    region: 'Kintamani, Bangli, Bali',
    altitude: '1,200 - 1,500 MASL',
    varietal: 'S-795, Kopyol',
    process: 'Full Washed',
    roastLevel: 'Medium',
    tastingNotes: ['Chocolate', 'Brown Sugar', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Sweet', 'Fruity'],
    description: 'Arabika klasik Bali dengan profil sangrai medium. Menghasilkan espresso yang seimbang dengan aroma cokelat susu, gula karamel, dan body yang mantap.',
    story: 'Ditanam di bawah naungan pohon jeruk di dataran tinggi vulkanik Kintamani. Memberikan hint keasaman sitrus lembut yang menyatu harmonis dengan susu hangat.',
    basePrice: 70000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 70000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 135000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg (Hopper Size)', price: 260000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop',
    acidity: 2,
    sweetness: 4,
    body: 4,
    brewingRecipe: {
      method: 'Modern Espresso (Flat White / Latte)',
      dose: '19g',
      water: '38g out',
      ratio: '1:2',
      temp: '93°C',
      time: '26 - 30 detik',
      steps: [
        'Dosing 19g kopi giling halus.',
        'Pre-infusion 5 detik pada 3 bar.',
        'Full pressure 9 bar hingga mencapai 38 gram espresso.',
        'Steam susu hingga silky microfoam 60°C.',
      ],
    },
  },
  {
    id: 'espresso-brazil-santos',
    slug: 'brazil-santos-arabica',
    name: 'Brazil Santos (Arabica)',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Espresso Roast',
    origin: 'Brazil',
    region: 'Santos, Minas Gerais',
    altitude: '1,000 - 1,200 MASL',
    varietal: 'Mundo Novo, Catuai',
    process: 'Natural / Pulped Natural',
    roastLevel: 'Medium-Dark',
    tastingNotes: ['Earthy', 'Dark Chocolate', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Nutty'],
    description: 'Fondasi espresso klasik dunia. Sensasi cokelat hitam pekat, aroma kacang panggang, dan aftertaste earthy yang tebal dan nyaman.',
    story: 'Diimpor langsung dari kawasan penghasil kopi legendaris Minas Gerais Brazil. Pilihan tepat untuk americano hangat yang mantap atau latte yang creamy gurih.',
    basePrice: 92000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 92000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 175000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg (Hopper Size)', price: 340000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?q=80&w=800&auto=format&fit=crop',
    acidity: 1,
    sweetness: 3,
    body: 5,
    brewingRecipe: {
      method: 'Classic Espresso & Moka Pot',
      dose: '18g',
      water: '36g out',
      ratio: '1:2',
      temp: '92°C',
      time: '25 - 28 detik',
      steps: [
        'Ekstraksi espresso pada rasio 1:2.',
        'Sangat pas untuk menu Cappuccino, Iced Americano, atau Mocaccino.',
      ],
    },
  },
];

export const SERIES_LIST = [
  'All Series',
  'Ijen Series',
  'Sunda Series',
  'Java Exotic',
  'Grand Reserve',
  'Espresso Roast',
] as const;

export const FLAVOR_CATEGORIES = [
  'All Flavors',
  'Fruity',
  'Floral',
  'Chocolaty',
  'Nutty',
  'Sweet',
] as const;

export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatPriceAbbr(amount: number): string {
  if (amount >= 1000) {
    return `${amount / 1000}K`;
  }
  return amount.toString();
}

export function getProductBySlug(slug: string): CoffeeProduct | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
