export interface ProductVariant {
  weightGrams: number;
  weightLabel: string;
  price: number;
  inStock: boolean;
}

export type GrindOption = 'whole' | 'coarse' | 'medium' | 'fine';

export interface GrindOptionDetail {
  id: GrindOption;
  label: string;
  description: string;
  recommendedFor: string;
}

export const GRIND_OPTIONS: GrindOptionDetail[] = [
  {
    id: 'whole',
    label: 'Whole Beans',
    description: 'Biji utuh segar untuk digiling sendiri sebelum seduh.',
    recommendedFor: 'Maksimum freshness & grinder manual/otomatis',
  },
  {
    id: 'coarse',
    label: 'Coarse Grind',
    description: 'Gilingan kasar dengan partikel menyerupai sea salt kasar.',
    recommendedFor: 'French Press, Cold Brew, Cupping',
  },
  {
    id: 'medium',
    label: 'Medium Grind',
    description: 'Gilingan sedang sehalus pasir pantai bersih.',
    recommendedFor: 'V60, Kalita Wave, Aeropress, Clever Dripper',
  },
  {
    id: 'fine',
    label: 'Fine Grind',
    description: 'Gilingan halus bertekstur bubuk gula halus / tepung.',
    recommendedFor: 'Espresso Machine, Moka Pot, Tubruk Halus',
  },
];

export interface BrewRecipe {
  method: string;
  dose: string;
  water: string;
  ratio: string;
  temp: string;
  time: string;
  steps: string[];
}

export type CoffeeSeries =
  | 'Ijen Series'
  | 'Enrekang Series'
  | 'Sunda Series'
  | 'Java Exotic'
  | 'Dewata Series'
  | 'Aceh Series'
  | 'Argopuro Walida'
  | 'Arjuna Series'
  | 'Grand Reserve'
  | 'Robusta Espresso'
  | 'Arabica Espresso'
  | 'Espresso Roast';

export interface CoffeeProduct {
  id: string;
  slug: string;
  name: string;
  slowbarAlias?: string;
  category: 'filter' | 'espresso' | 'reserve';
  categoryLabel: string;
  series: CoffeeSeries;
  origin: string;
  region: string;
  altitude: string;
  varietal: string;
  process: string;
  roastLevel: 'Light' | 'Light-Medium' | 'Medium-Light' | 'Medium' | 'Medium-Dark';
  tastingNotes: string[];
  flavorCategory: ('Fruity' | 'Floral' | 'Chocolaty' | 'Nutty' | 'Sweet' | 'Spicy')[];
  description: string;
  story: string;
  variants: ProductVariant[];
  basePrice: number;
  cupPrice?: number;
  defaultWeight: string;
  imageUrl: string;
  badge?: string;
  acidity: number; // 1-5
  sweetness: number; // 1-5
  body: number; // 1-5
  brewingRecipe: BrewRecipe;
  isFreshCrop?: boolean;
  isFeatured?: boolean;
  isSoldOut?: boolean;
}

export const PRODUCTS: CoffeeProduct[] = [
  // ==========================================
  // 1. IJEN SERIES (Filter Based)
  // ==========================================
  {
    id: 'ijen-cm-asmara',
    slug: 'ijen-carbonic-maceration-asmara',
    name: 'Ijen Carbonic Maceration (Asmara)',
    slowbarAlias: 'ASMARA',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Gunung Ijen, Banyuwangi - Bondowoso',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika, USDA 762',
    process: 'Carbonic Maceration',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Peach', 'Jasmine', 'Rich Taste', 'Medium Body'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Fermentasi anaerobik bertekanan karbon dioksida terkontrol menghasilkan aroma floral melati intens dipadukan manisnya buah persik matang dan body yang kaya.',
    story: 'Dipanen dari lereng kaldera aktif Gunung Ijen oleh petani binaan 52 Coffee. Ceri merah pilihan diproses dalam tangki stainless steel bertekanan CO2 murni.',
    basePrice: 65000,
    cupPrice: 38000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 65000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 120000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 320000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Signature Ijen',
    acidity: 4,
    sweetness: 4,
    body: 3,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 15s',
      steps: [
        '00:00 - 00:40: Blooming 45g air, swirl lembut 5 detik.',
        '00:40 - 01:15: Tuang kedua hingga 135g gerakan spiral perlahan.',
        '01:15 - 02:00: Tuang ketiga hingga 225g memusat.',
        '02:15: Selesai, nikmati aroma jasmine dan manis buah peach.',
      ],
    },
  },
  {
    id: 'ijen-kenyan-wening',
    slug: 'ijen-kenyan-wening',
    name: 'Ijen Kenyan (Wening)',
    slowbarAlias: 'WENING',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Gunung Ijen, Bondowoso',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika / Typica',
    process: 'Kenyan Process (Double Washed)',
    roastLevel: 'Light',
    tastingNotes: ['Clean', 'Jasmine', 'Crisp Citrus'],
    flavorCategory: ['Floral', 'Fruity'],
    description: 'Seduhan yang sangat jernih (clean cup) dengan karakter bunga melati merekah dan keasaman sitrus yang menyegarkan khas proses wash bergaya Kenya.',
    story: 'Mengadopsi metode perendaman ganda (double soak) khas Kenya di lereng Ijen untuk memurnikan rasa manis alami biji kopi.',
    basePrice: 59000,
    cupPrice: 30000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 59000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 109000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 290000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
    badge: 'Clean Cup',
    acidity: 5,
    sweetness: 4,
    body: 2,
    isFreshCrop: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '240ml',
      ratio: '1:16',
      temp: '93°C',
      time: '2m 10s',
      steps: [
        '00:00 - 00:35: Blooming 45g air panas.',
        '00:35 - 01:10: Tuang deras melingkar sampai 140g.',
        '01:10 - 01:50: Tuang akhir perlahan hingga 240g.',
        '02:10: Nikmati karakter citrus yang crispy dan clean.',
      ],
    },
  },
  {
    id: 'ijen-anaerob-rahsa',
    slug: 'ijen-anaerob-rahsa',
    name: 'Ijen Anaerob (Rahsa)',
    slowbarAlias: 'RAHSA',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Gunung Ijen, Bondowoso',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika',
    process: 'Anaerobic Natural',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Tropical', 'Fermented Sweetness', 'Complex'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Kekayaan rasa tropis dengan manis fermentasi buah yang padat, aroma semerbak, dan kompleksitas rasa yang memikat.',
    story: 'Fermentasi ceri utuh tanpa oksigen selama 96 jam untuk memaksimalkan sweetness dan body kompleks khas roastery 52.',
    basePrice: 59000,
    cupPrice: 35000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 59000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 109000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 290000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 3,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'Kalita Wave',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 20s',
      steps: ['Blooming 40g (40s)', 'Tuang sampai 130g', 'Tuang sampai 225g'],
    },
  },
  {
    id: 'ijen-lactic-laras',
    slug: 'ijen-lactic-laras',
    name: 'Ijen Lactic (Laras)',
    slowbarAlias: 'LARAS',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Kawah Ijen, Bondowoso',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika',
    process: 'Lactic Process',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Mango', 'Lychee', 'Lime', 'Creamy', 'Chocolate'],
    flavorCategory: ['Fruity', 'Sweet', 'Chocolaty'],
    description: 'Sensasi rasa mangga ranum dan leci berpadu keasaman segar jeruk nipis, diakhiri dengan tekstur creamy bagai cokelat susu.',
    story: 'Kultur bakteri asam laktat murni dalam bejana tertutup memecah musilase ceri secara lembut dan menghasilkan body creamy istimewa.',
    basePrice: 59000,
    cupPrice: 35000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 59000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 109000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 290000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'Origami / V60',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 25s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 140g', 'Tuang sampai 225g'],
    },
  },
  {
    id: 'ijen-yellow-bourbon-kencana',
    slug: 'ijen-yellow-bourbon-kencana',
    name: 'Ijen Yellow Bourbon (Kencana)',
    slowbarAlias: 'KENCANA',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Gunung Ijen, Bondowoso',
    altitude: '1,500 MASL',
    varietal: 'Yellow Bourbon',
    process: 'Honey Process',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Honey', 'Almond', 'Smooth Body'],
    flavorCategory: ['Sweet', 'Nutty'],
    description: 'Varietas langka Yellow Bourbon dengan kelembutan madu hutan dan gurihnya kacang almond panggang dalam body yang halus.',
    story: 'Biji ceri kuning keemasan yang manis alami, dipetik saat brix kematangan mencapai puncaknya.',
    basePrice: 59000,
    cupPrice: 30000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 59000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 109000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 290000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 3,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '240ml',
      ratio: '1:16',
      temp: '92°C',
      time: '2m 15s',
      steps: ['Blooming 45g (35s)', 'Tuang perlahan sampai 150g', 'Tuang akhir sampai 240g'],
    },
  },
  {
    id: 'ijen-full-wash-washey',
    slug: 'ijen-full-wash-washey',
    name: 'Ijen Full Wash (Washey)',
    slowbarAlias: 'WASHEY',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Ijen Series',
    origin: 'East Java, Indonesia',
    region: 'Gunung Ijen, Bondowoso',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika / USDA',
    process: 'Full Wash',
    roastLevel: 'Medium-Light',
    tastingNotes: ['Balanced', 'Mild', 'Acidity', 'Nutty'],
    flavorCategory: ['Nutty', 'Sweet'],
    description: 'Profil seduhan klasik Ijen yang seimbang, keasaman lembut, dengan sentuhan rasa nutty hangat yang bersahabat untuk harian.',
    story: 'Pilihan seduhan harian pecinta filter coffee dengan kejernihan rasa dan aftertaste yang bersih.',
    basePrice: 59000,
    cupPrice: 25000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 59000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 109000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 290000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 3,
    sweetness: 3,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '90°C',
      time: '2m 15s',
      steps: ['Blooming 40g (40s)', 'Tuang kedua sampai 135g', 'Tuang akhir sampai 225g'],
    },
  },

  // ==========================================
  // 2. ENREKANG SERIES (Sulawesi)
  // ==========================================
  {
    id: 'buntu-lenta-wash-duharman',
    slug: 'buntu-lenta-wash-duharman',
    name: 'Buntu Lenta Wash (Duharman Wash)',
    slowbarAlias: 'DUHARMAN WASH',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Enrekang Series',
    origin: 'South Sulawesi, Indonesia',
    region: 'Buntu Lenta, Enrekang',
    altitude: '1,500 - 1,800 MASL',
    varietal: 'Typica, S-795',
    process: 'Wash Process',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Mandarin', 'Honey', 'Caramel', 'Floral'],
    flavorCategory: ['Fruity', 'Floral', 'Sweet'],
    description: 'Kopi legendaris Enrekang dengan manis madu pekat, aroma bunga pegunungan, dan keasaman segar buah jeruk mandarin.',
    story: 'Dikelola oleh petani pelopor Duharman di dataran tinggi Buntu Lenta, Enrekang, Sulawesi Selatan.',
    basePrice: 109000,
    cupPrice: 45000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 109000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 199000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 439000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Sulawesi Special',
    acidity: 4,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 20s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 140g', 'Tuang sampai 225g'],
    },
  },
  {
    id: 'buntu-lenta-wine-duharman',
    slug: 'buntu-lenta-wine-duharman',
    name: 'Buntu Lenta Wine (Duharman Winey)',
    slowbarAlias: 'DUHARMAN WINEY',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Enrekang Series',
    origin: 'South Sulawesi, Indonesia',
    region: 'Buntu Lenta, Enrekang',
    altitude: '1,500 - 1,800 MASL',
    varietal: 'Typica, S-795',
    process: 'Wine Processed',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Wine', 'Tangerine', 'Caramel'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Fermentasi ceri utuh berlapis menciptakan sensasi winey berkelas dengan manis karamel dan kesegaran jeruk keprok.',
    story: 'Biji kopi pilihan yang dijemur perlahan bersama kulit buah hingga meresapkan gula alami ke dalam inti biji.',
    basePrice: 115000,
    cupPrice: 52000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 115000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 215000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 459000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'Kalita Wave',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 30s',
      steps: ['Blooming 45g (45s)', 'Tuang bertahap hingga 225g'],
    },
  },
  {
    id: 'buntu-lenta-natural-duharman',
    slug: 'buntu-lenta-natural-duharman',
    name: 'Buntu Lenta Natural (Duharman Natural)',
    slowbarAlias: 'DUHARMAN NATURAL',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Enrekang Series',
    origin: 'South Sulawesi, Indonesia',
    region: 'Buntu Lenta, Enrekang',
    altitude: '1,500 - 1,800 MASL',
    varietal: 'Typica, S-795',
    process: 'Natural Process',
    roastLevel: 'Light',
    tastingNotes: ['Blueberry', 'Strawberry', 'Bold Body', 'Sweetness'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Ledakan aroma buah beri ungu, stroberi manis, serta body yang tebal dan memanjakan lidah.',
    story: 'Hasil penjemuran di atas raised bed terlindung sinar matahari langsung di pegunungan Enrekang.',
    basePrice: 109000,
    cupPrice: 45000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 109000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 199000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 439000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 135g', 'Tuang sampai 225g'],
    },
  },
  {
    id: 'kalaciri-wash-process',
    slug: 'kalaciri-wash-process',
    name: 'Kalaciri Wash Process',
    slowbarAlias: 'KALACIRI',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Enrekang Series',
    origin: 'South Sulawesi, Indonesia',
    region: 'Kalaciri Dammang, Enrekang',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Typica, S-795',
    process: 'Kalaciri Dammang Wash Process',
    roastLevel: 'Medium-Light',
    tastingNotes: ['Palm Sugar', 'Sweet Spicy', 'Chocolate'],
    flavorCategory: ['Sweet', 'Spicy', 'Chocolaty'],
    description: 'Manisnya gula aren hangat berpadu dengan rempah manis aromatik dan aftertaste cokelat lembut.',
    story: 'Karakter tradisional Sulawesi yang diolah dengan standar ketat washing station Kalaciri Dammang.',
    basePrice: 99000,
    cupPrice: 35000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 99000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 185000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 399000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 2,
    sweetness: 4,
    body: 4,
    brewingRecipe: {
      method: 'Aeropress / V60',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '90°C',
      time: '2m 00s',
      steps: ['Tuang 100g aduk pelan', 'Tuang hingga 240g press lembut'],
    },
  },
  {
    id: 'benteng-alla-wash-sembada',
    slug: 'benteng-alla-wash-sembada',
    name: 'Benteng Alla Wash (Sembada)',
    slowbarAlias: 'SEMBADA',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Enrekang Series',
    origin: 'South Sulawesi, Indonesia',
    region: 'Benteng Alla, Enrekang',
    altitude: '1,600 - 1,800 MASL',
    varietal: 'S-795',
    process: 'Benteng Alla Wash Process',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Lime', 'Brown Sugar', 'Cashew', 'Caramel', 'Tamarind'],
    flavorCategory: ['Fruity', 'Sweet', 'Nutty'],
    description: 'Kompleksitas tinggi dengan keasaman segar jeruk nipis dan asam jawa, diimbangi manis gula merah dan gurih kacang mete.',
    story: 'Berasal dari kawasan hutan lindung Benteng Alla dengan ketinggian ekstrem di Sulawesi.',
    basePrice: 115000,
    cupPrice: 50000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 115000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 215000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 459000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 4,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 15s',
      steps: ['Blooming 45g', 'Tuang melingkar sampai 135g', 'Tuang memusat sampai 225g'],
    },
  },

  // ==========================================
  // 3. SUNDA SERIES (West Java)
  // ==========================================
  {
    id: 'puntang-honey-gulali',
    slug: 'puntang-honey-gulali',
    name: 'Puntang Honey (Gulali)',
    slowbarAlias: 'GULALI',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Sunda Series',
    origin: 'West Java, Indonesia',
    region: 'Gunung Puntang, Bandung',
    altitude: '1,300 - 1,600 MASL',
    varietal: 'Typica, Sigarar Utang',
    process: 'Puntang Honey Process',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Honey', 'Peach', 'Chocolate-Like'],
    flavorCategory: ['Sweet', 'Fruity', 'Chocolaty'],
    description: 'Manis pekat bagai permen gulali dan madu bunga, berpadu buah persik dan sentuhan cokelat manis.',
    story: 'Kebun legendaris Gunung Puntang Jawa Barat yang pernah memenangkan penghargaan Specialty Coffee dunia di Atlanta.',
    basePrice: 95000,
    cupPrice: 45000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 95000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 179000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 379000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 3,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '16g',
      water: '250ml',
      ratio: '1:15.6',
      temp: '92°C',
      time: '2m 30s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 150g', 'Tuang sampai 250g'],
    },
  },
  {
    id: 'puntang-natural-aromanis',
    slug: 'puntang-natural-aromanis',
    name: 'Puntang Natural (Aromanis)',
    slowbarAlias: 'AROMANIS',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Sunda Series',
    origin: 'West Java, Indonesia',
    region: 'Gunung Puntang, Bandung',
    altitude: '1,300 - 1,600 MASL',
    varietal: 'Typica, Ateng Super',
    process: 'Puntang Natural Process',
    roastLevel: 'Light',
    tastingNotes: ['Pineapple', 'Berry', 'Jackfruit'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Aroma harum buah nanas matang, nangka manis, dan aneka beri tropis yang semerbak sejak pertama kali digiling.',
    story: 'Diproses natural tradisional dengan penjemuran bertahap di bawah kanopi pegunungan Puntang.',
    basePrice: 99000,
    cupPrice: 52000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 99000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 185000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 399000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 135g', 'Tuang sampai 225g'],
    },
  },

  // ==========================================
  // 4. JAVA EXOTIC SERIES (Experimental Yeast & Fermentation)
  // ==========================================
  {
    id: 'sumbing-supernova-celestia',
    slug: 'sumbing-supernova-celestia',
    name: 'Sumbing Supernova Wash (Celestia)',
    slowbarAlias: 'CELESTIA',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Sumbing',
    altitude: '1,500 - 1,700 MASL',
    varietal: 'Kartika / Typica',
    process: 'Sumbing Supernova Wash',
    roastLevel: 'Light',
    tastingNotes: ['Explosive Berry', 'Complex', 'Candy-Like'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Ledakan rasa buah beri manis yang luar biasa intens bagai permen buah, dengan tingkat kompleksitas spektakuler.',
    story: 'Lini eksperimental roastery 52 memadukan fermentasi supernova wash terkontrol di lereng Gunung Sumbing.',
    basePrice: 139000,
    cupPrice: 48000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Experimental Favorite',
    acidity: 5,
    sweetness: 5,
    body: 3,
    isFeatured: true,
    brewingRecipe: {
      method: 'Origami / V60',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 10s',
      steps: ['Blooming 45g (40s)', 'Tuang spiral ke 140g', 'Tuang akhir ke 225g'],
    },
  },
  {
    id: 'prau-natural-surya',
    slug: 'prau-natural-el-davisio-surya',
    name: 'Prau Natural El Davisio Double Mosto (Surya)',
    slowbarAlias: 'SURYA',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Prau',
    altitude: '1,600 - 1,800 MASL',
    varietal: 'El Davisio Selection',
    process: 'Double Mosto Triple Yeast',
    roastLevel: 'Light',
    tastingNotes: ['White Floral', 'Strawberry', 'Candy Mint'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Aroma bunga putih elegan, manis buah stroberi ranum, dan sensasi semilir candy mint di ujung lidah.',
    story: 'Fermentasi ceri dengan inokulasi double mosto dan tiga ragi pilihan menghasilkan sensasi seduh yang amat memukau.',
    basePrice: 139000,
    cupPrice: 60000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Triple Yeast',
    acidity: 4,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '230ml',
      ratio: '1:15.3',
      temp: '92°C',
      time: '2m 15s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 140g', 'Tuang sampai 230g'],
    },
  },
  {
    id: 'prau-not-chiroso-unchiro',
    slug: 'prau-not-chiroso-unchiro',
    name: 'Prau Not-Chiroso Style (Unchiro)',
    slowbarAlias: 'UNCHIRO',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Prau',
    altitude: '1,600 - 1,800 MASL',
    varietal: 'Selected Typica Prau',
    process: 'Prau Not-Chiroso Style Fermentation',
    roastLevel: 'Light',
    tastingNotes: ['Tropical', 'Floral', 'Pineapple-Jasmine'],
    flavorCategory: ['Floral', 'Fruity'],
    description: 'Profil rasa menyerupai varietas Chiroso Kolombia dengan perpaduan tropical nanas segar dan wangi melati pekat.',
    story: 'Eksperimen profil rasa bergaya Chiroso pertama dari lereng Gunung Prau.',
    basePrice: 139000,
    cupPrice: 56000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 139000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 259000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 4,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: ['Blooming 45g (40s)', 'Tuang ke 135g', 'Tuang ke 225g'],
    },
  },
  {
    id: 'sindoro-strawberry-selai',
    slug: 'sindoro-strawberry-selai',
    name: 'Sindoro Strawberry Triple Yeast (Selai)',
    slowbarAlias: 'SELAI',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Sindoro',
    altitude: '1,500 - 1,700 MASL',
    varietal: 'Kartika',
    process: 'Sindoro Strawberry Triple Yeast',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Sweet Jammy Strawberry', 'Vanilla'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Karakter selai stroberi manis yang amat lezat berpadu aroma vanila hangat yang creamy dan lembut.',
    story: 'Fermentasi tiga ragi khusus pada ceri Sindoro yang menghasilkan aroma strawberry jam pekat.',
    basePrice: 119000,
    cupPrice: 56000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 119000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 220000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Sweet Jammy',
    acidity: 3,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'V60 / Kalita',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 20s',
      steps: ['Blooming 45g (40s)', 'Tuang kedua ke 140g', 'Tuang akhir ke 225g'],
    },
  },
  {
    id: 'sindoro-lavender-candy',
    slug: 'sindoro-lavender-candy',
    name: 'Sindoro Lavender Candy Wash (Lavender)',
    slowbarAlias: 'LAVENDER',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Java Exotic',
    origin: 'Central Java, Indonesia',
    region: 'Gunung Sindoro',
    altitude: '1,500 - 1,700 MASL',
    varietal: 'Kartika / Typica',
    process: 'Candy Wash Triple Yeast Double Ferment',
    roastLevel: 'Light',
    tastingNotes: ['Purple Flower', 'Peach', 'Guava', 'Pome Candy'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Aroma bunga ungu semerbak, manisnya buah persik, jambu biji ranum, serta permen delima yang unik.',
    story: 'Inovasi double fermentation dengan sentuhan floral lavender alami dari ketinggian Sindoro.',
    basePrice: 119000,
    cupPrice: 55000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 119000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 220000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'Origami / V60',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: ['Blooming 45g', 'Tuang sampai 135g', 'Tuang sampai 225g'],
    },
  },

  // ==========================================
  // 5. ARGOPURO WALIDA SERIES (East Java Micro-Lot)
  // ==========================================
  {
    id: 'argopuro-walida-anaerob-arcapada',
    slug: 'argopuro-walida-anaerob-arcapada',
    name: 'Argopuro Natural Anaerob (Arcapada)',
    slowbarAlias: 'ARCAPADA',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Argopuro Walida',
    origin: 'East Java, Indonesia',
    region: 'Gunung Argopuro, Probolinggo',
    altitude: '1,300 - 1,600 MASL',
    varietal: 'Kartika, Typica',
    process: 'Argopuro Natural Anaerob',
    roastLevel: 'Light',
    tastingNotes: ['Intensely Sweet', 'Boozy', 'Candy Like Fruit'],
    flavorCategory: ['Sweet', 'Fruity'],
    description: 'Manis yang sangat intens dengan sentuhan boozy elegan dan cita rasa buah tropis bagai permen.',
    story: 'Koleksi mikro-lot petani binaan Walida di lembah Argopuro Jawa Timur.',
    basePrice: 80000,
    cupPrice: 50000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 80000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 150000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Walida Micro-lot',
    acidity: 4,
    sweetness: 5,
    body: 4,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: ['Blooming 45g (40s)', 'Tuang spiral ke 135g', 'Tuang tengah ke 225g'],
    },
  },
  {
    id: 'damarkandang-cm-kismis',
    slug: 'damarkandang-cm-kismis',
    name: 'Damarkandang Carbonic Maceration Kismis',
    slowbarAlias: 'DAMARKANDANG KISMIS',
    category: 'filter',
    categoryLabel: 'Filter Based',
    series: 'Argopuro Walida',
    origin: 'East Java, Indonesia',
    region: 'Damarkandang, Argopuro',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Kartika',
    process: 'Damarkandang Carbonic Maceration',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Intensely Sweet', 'Winey', 'Candy Like Cup'],
    flavorCategory: ['Sweet', 'Fruity'],
    description: 'Karakter rasa manis buah kismis hitam yang pekat, sentuhan winey yang halus, dan cangkir yang luar biasa manis.',
    story: 'Fermentasi CO2 ceri kismis hasil seleksi ketat di dusun Damarkandang.',
    basePrice: 90000,
    cupPrice: 60000,
    defaultWeight: '100g',
    variants: [
      { weightGrams: 100, weightLabel: '100g', price: 90000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 175000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'Kalita Wave / V60',
      dose: '15g',
      water: '225ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 20s',
      steps: ['Blooming 45g (40s)', 'Tuang bertahap sampai 225g'],
    },
  },

  // ==========================================
  // 6. GRAND RESERVE MICRO-LOT SERIES (International & Competition)
  // ==========================================
  {
    id: 'grand-reserve-el-triunfo-geisha',
    slug: 'el-triunfo-geisha-tolima-aurora',
    name: 'El Triunfo Geisha Tolima (Aurora)',
    slowbarAlias: 'AURORA',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Colombia',
    region: 'Tolima, Colombia',
    altitude: '1,800 - 2,000 MASL',
    varietal: 'Geisha (Gesha)',
    process: 'Washed Extended Fermentation',
    roastLevel: 'Light',
    tastingNotes: ['Jasmine', 'Bergamot', 'Peach', 'Tea-like', 'Crystalline'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Puncak kemewahan rasa kopi dunia. Aroma melati yang semerbak, keanggunan minyak bergamot earl grey, manisnya buah peach putih, dan kejernihan crystalline yang tiada tara.',
    story: 'Ditanam di ketinggian 2.000 meter di Finca El Triunfo, Tolima, Kolombia. Varietas Geisha legendaris pemenang berbagai kompetisi World Brewers Cup.',
    basePrice: 86000,
    cupPrice: 200000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 86000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 200000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 380000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 709000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'World Competition Geisha',
    acidity: 5,
    sweetness: 5,
    body: 2,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'Hario V60 Plastic / Origami',
      dose: '16g',
      water: '256ml',
      ratio: '1:16',
      temp: '93°C',
      time: '2m 15s',
      steps: [
        '00:00 - 00:45: Blooming 50g air suhu 93°C, swirl lembut 3 detik.',
        '00:45 - 01:15: Tuang tengah lembut memutar hingga 150g.',
        '01:15 - 01:50: Tuang akhir ke titik tengah hingga 256g.',
        '02:15: Drawdown selesai. Sajikan di sensory cup untuk menangkap aroma bergamot & jasmine.',
      ],
    },
  },
  {
    id: 'grand-reserve-magnum-sidra',
    slug: 'magnum-sidra-el-vergel-soberano',
    name: 'Magnum Sidra El Vergel Cauca (Soberano)',
    slowbarAlias: 'SOBERANO',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Colombia',
    region: 'Cauca, Colombia',
    altitude: '1,850 MASL',
    varietal: 'Sidra (Bourbon x Typica Heirloom)',
    process: 'Anaerobic Natural Koji Co-Ferment',
    roastLevel: 'Light',
    tastingNotes: ['Tropical', 'Syrup', 'Layered Cocoa', 'Brown Sugar'],
    flavorCategory: ['Fruity', 'Chocolaty', 'Sweet'],
    description: 'Varietas langka Sidra dengan rasa sirup tropis pekat, lapisan rasa kakao mewah, dan aftertaste brown sugar yang amat panjang.',
    story: 'Mahakarya perkebunan El Vergel Cauca Kolombia yang dibudidayakan secara eksklusif untuk ajang kejuaraan barista dunia.',
    basePrice: 72000,
    cupPrice: 180000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 72000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 180000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 350000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 685000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Competition Sidra',
    acidity: 4,
    sweetness: 5,
    body: 4,
    isFreshCrop: true,
    isFeatured: true,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '92°C',
      time: '2m 10s',
      steps: ['Blooming 50g (40s)', 'Tuang spiral ke 140g', 'Tuang akhir ke 240g'],
    },
  },
  {
    id: 'grand-reserve-sudan-rume-carmin',
    slug: 'sudan-rume-huila-carmin',
    name: 'Sudan Rume Huila (Carmin)',
    slowbarAlias: 'CARMIN',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Colombia',
    region: 'Huila, Colombia',
    altitude: '1,750 - 1,900 MASL',
    varietal: 'Sudan Rume',
    process: 'Natural Fermented',
    roastLevel: 'Light',
    tastingNotes: ['Deepberry', 'Wine-Like', 'Red Fruit'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Varietas kuno Sudan Rume yang sangat langka dengan rasa buah beri gelap pekat, sentuhan winey yang anggun, dan buah merah ranum.',
    story: 'Varietas liar asli dari dataran tinggi Boma Plateau Sudan yang dibudidayakan di tanah vulkanis Huila Kolombia.',
    basePrice: 80000,
    cupPrice: 180000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 80000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 185000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 360000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 690000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'Kalita Wave / V60',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 20s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 140g', 'Tuang sampai 240g'],
    },
  },
  {
    id: 'grand-reserve-pink-bourbon-marfil',
    slug: 'inmaculada-pink-bourbon-marfil',
    name: 'Inmaculada Pink Bourbon Huila (Marfil)',
    slowbarAlias: 'MARFIL',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Colombia',
    region: 'Huila, Colombia',
    altitude: '1,800 MASL',
    varietal: 'Pink Bourbon',
    process: 'Inmaculada Washed',
    roastLevel: 'Light',
    tastingNotes: ['Honey Peach', 'White Blossom', 'Refine Elegance'],
    flavorCategory: ['Floral', 'Fruity', 'Sweet'],
    description: 'Keanggunan mutlak rasa buah peach bersalut madu dan aroma semerbak bunga putih mekar dalam seduhan yang sangat halus.',
    story: 'Karya kebun ternama Finca Inmaculada yang terkenal di seluruh dunia dalam memproduksi lot kopi mikro paling elegan.',
    basePrice: 62000,
    cupPrice: 140000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 62000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 177000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 348000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 687000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 4,
    sweetness: 5,
    body: 3,
    brewingRecipe: {
      method: 'V60 Pour Over',
      dose: '16g',
      water: '256ml',
      ratio: '1:16',
      temp: '92°C',
      time: '2m 15s',
      steps: ['Blooming 45g (40s)', 'Tuang spiral ke 150g', 'Tuang akhir ke 256g'],
    },
  },
  {
    id: 'grand-reserve-yemen-sahara',
    slug: 'yemen-haraz-golden-harvest-sahara',
    name: 'Yemen Haraz Golden Harvest (Sahara)',
    slowbarAlias: 'SAHARA',
    category: 'reserve',
    categoryLabel: 'Grand Reserve',
    series: 'Grand Reserve',
    origin: 'Yemen',
    region: 'Haraz Mountain, Yemen',
    altitude: '2,000 - 2,200 MASL',
    varietal: 'Yemenia / Udaini Heirloom',
    process: 'Traditional Rooftop Natural',
    roastLevel: 'Light-Medium',
    tastingNotes: ['Sweet Jammy Strawberry', 'Vanilla'],
    flavorCategory: ['Fruity', 'Sweet'],
    description: 'Biji kopi tertua di dunia dari pegunungan tinggi Haraz Yaman. Manisnya selai stroberi pekat berpadu sentuhan vanila rempah magis.',
    story: 'Dipanen dari pohon kopi purba di terasering pegunungan Haraz Yaman pada ketinggian lebih dari 2.000 meter.',
    basePrice: 59000,
    cupPrice: 99000,
    defaultWeight: '16g',
    variants: [
      { weightGrams: 16, weightLabel: '16g (Tasting Dose)', price: 59000, inStock: true },
      { weightGrams: 50, weightLabel: '50g', price: 165000, inStock: true },
      { weightGrams: 100, weightLabel: '100g', price: 229000, inStock: true },
      { weightGrams: 200, weightLabel: '200g', price: 549000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Ancient Yemenia',
    acidity: 4,
    sweetness: 5,
    body: 4,
    brewingRecipe: {
      method: 'Origami / V60',
      dose: '16g',
      water: '240ml',
      ratio: '1:15',
      temp: '91°C',
      time: '2m 15s',
      steps: ['Blooming 45g (40s)', 'Tuang sampai 140g', 'Tuang sampai 240g'],
    },
  },

  // ==========================================
  // 7. ESPRESSO BASED ROAST PROFILES (Robusta & Arabica)
  // ==========================================
  {
    id: 'espresso-dampit-natural',
    slug: 'dampit-natural-espresso',
    name: 'Dampit Natural Robusta Espresso',
    slowbarAlias: 'DAMPIT NATURAL',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Robusta Espresso',
    origin: 'East Java, Indonesia',
    region: 'Dampit, Malang',
    altitude: '700 - 900 MASL',
    varietal: 'Fine Robusta Malang',
    process: 'Natural Process',
    roastLevel: 'Medium-Dark',
    tastingNotes: ['Chocolate', 'Brown Sugar', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Sweet'],
    description: 'Robusta terbaik kebanggaan Malang dengan body tebal mantap, aroma cokelat pekat, dan manis brown sugar yang pas untuk es kopi susu.',
    story: 'Karya petani Dampit Malang Selatan yang diproses petik merah untuk menghasilkan fine robusta tanpa rasa getir berlebih.',
    basePrice: 35000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 35000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 85000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg', price: 150000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'Best for Milk Based',
    acidity: 1,
    sweetness: 4,
    body: 5,
    brewingRecipe: {
      method: 'Espresso Machine / Moka Pot',
      dose: '18g - 20g',
      water: '38g - 40g yield',
      ratio: '1:2',
      temp: '93°C',
      time: '25 - 30s',
      steps: [
        'Grind fine merata dengan WDT tool.',
        'Tamping konsisten 15kg.',
        'Ekstraksi 38g espresso dalam 26 detik.',
        'Padukan dengan 120ml fresh milk dingin dan 20ml gula aren cair.',
      ],
    },
  },
  {
    id: 'espresso-telemung-honey',
    slug: 'telemung-honey-robusta-espresso',
    name: 'Telemung Honey Robusta Espresso',
    slowbarAlias: 'TELEMUNG HONEY',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Robusta Espresso',
    origin: 'East Java, Indonesia',
    region: 'Telemung, Banyuwangi',
    altitude: '600 - 800 MASL',
    varietal: 'Fine Robusta Banyuwangi',
    process: 'Honey Process',
    roastLevel: 'Medium-Dark',
    tastingNotes: ['Sweet Chocolate', 'Brown Sugar', 'Medium Body'],
    flavorCategory: ['Sweet', 'Chocolaty'],
    description: 'Robusta proses madu dari Telemung dengan cita rasa manis cokelat susu, body lembut seimbang, dan aroma karamel yang gurih.',
    story: 'Berasal dari desa kopi Telemung Banyuwangi yang terkenal dengan tradisi olah kopi madu bernilai tinggi.',
    basePrice: 35000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 35000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 85000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg', price: 150000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 1,
    sweetness: 4,
    body: 4,
    brewingRecipe: {
      method: 'Espresso Machine',
      dose: '19g',
      water: '38g yield',
      ratio: '1:2',
      temp: '92°C',
      time: '26s',
      steps: ['Ekstraksi 38g yield espresso.', 'Campurkan dengan susu oat atau susu sapi segar.'],
    },
  },
  {
    id: 'espresso-arabica-kintamani',
    slug: 'kintamani-full-wash-arabica-espresso',
    name: 'Kintamani Full Wash Arabica Espresso',
    slowbarAlias: 'KINTAMANI FULL WASH',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Arabica Espresso',
    origin: 'Bali, Indonesia',
    region: 'Kintamani, Bali',
    altitude: '1,200 - 1,400 MASL',
    varietal: 'Typica, Kartika',
    process: 'Full Wash',
    roastLevel: 'Medium',
    tastingNotes: ['Chocolate', 'Brown Sugar', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Sweet'],
    description: 'Single origin Arabika Bali dengan profil sangrai espresso menghasilkan krema tebal, manis brown sugar, dan sentuhan cokelat hangat.',
    story: 'Ditanam berdampingan dengan pohon jeruk Kintamani yang terkenal akan kesuburan tanah vulkanis Danau Batur.',
    basePrice: 70000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 70000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 135000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg', price: 260000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 2,
    sweetness: 4,
    body: 4,
    brewingRecipe: {
      method: 'Espresso Machine',
      dose: '18g',
      water: '36g yield',
      ratio: '1:2',
      temp: '93°C',
      time: '28s',
      steps: ['Ekstraksi 36g espresso untuk Americano atau Cafe Latte yang manis seimbang.'],
    },
  },
  {
    id: 'espresso-arabica-gayo-full-wash',
    slug: 'gayo-full-wash-arabica-espresso',
    name: 'Gayo Full Wash Arabica Espresso',
    slowbarAlias: 'GAYO FULL WASH',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Arabica Espresso',
    origin: 'Aceh, Indonesia',
    region: 'Takengon, Aceh Tengah',
    altitude: '1,400 - 1,600 MASL',
    varietal: 'Timtim, Borbor',
    process: 'Full Wash',
    roastLevel: 'Medium-Dark',
    tastingNotes: ['Earthy', 'Dark Chocolate', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Spicy'],
    description: 'Karakter legendaris tanah Gayo dengan body yang sangat tebal, aroma rempah earthy yang harum, dan kekayaan dark chocolate.',
    story: 'Kopi Arabika organik terbaik dari perkebunan dataran tinggi Danau Laut Tawar Takengon.',
    basePrice: 75000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 75000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 140000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg', price: 265000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 1,
    sweetness: 3,
    body: 5,
    brewingRecipe: {
      method: 'Espresso Machine',
      dose: '19g',
      water: '38g yield',
      ratio: '1:2',
      temp: '92°C',
      time: '27s',
      steps: ['Ekstraksi 38g untuk Espresso murni atau Piccolo Latte yang kuat.'],
    },
  },
  {
    id: 'espresso-arabica-ijen-full-wash',
    slug: 'arabica-ijen-full-wash-espresso',
    name: 'Arabica Ijen Full Wash Espresso',
    slowbarAlias: 'ARABICA IJEN FULL WASH',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Arabica Espresso',
    origin: 'East Java, Indonesia',
    region: 'Gunung Ijen, Bondowoso',
    altitude: '1,400 MASL',
    varietal: 'Kartika / Typica',
    process: 'Full Wash',
    roastLevel: 'Medium',
    tastingNotes: ['Earthy', 'Dark Chocolate', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Nutty'],
    description: 'Espresso Arabika Ijen yang balance dengan crema cokelat keemasan, sentuhan cokelat hitam gurih, dan aftertaste yang bersih.',
    story: 'Roasting profil khusus dari biji Ijen pilihan untuk kebutuhan kedai kopi dan seduhan rumah.',
    basePrice: 60000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 60000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 140000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg', price: 250000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    badge: 'House Espresso',
    acidity: 2,
    sweetness: 4,
    body: 4,
    brewingRecipe: {
      method: 'Espresso Machine',
      dose: '18g',
      water: '36g yield',
      ratio: '1:2',
      temp: '93°C',
      time: '26s',
      steps: ['Ekstraksi 36g yield untuk Cappuccino dan Flat White yang creamy.'],
    },
  },
  {
    id: 'espresso-brazil-santos',
    slug: 'brazil-santos-espresso',
    name: 'Brazil Santos Espresso',
    slowbarAlias: 'BRAZIL SANTOS',
    category: 'espresso',
    categoryLabel: 'Espresso Based',
    series: 'Arabica Espresso',
    origin: 'Brazil',
    region: 'Minas Gerais, Santos, Brazil',
    altitude: '900 - 1,200 MASL',
    varietal: 'Mundo Novo, Catuai',
    process: 'Natural Process',
    roastLevel: 'Medium-Dark',
    tastingNotes: ['Earthy', 'Dark Chocolate', 'Full Body'],
    flavorCategory: ['Chocolaty', 'Nutty'],
    description: 'Kopi Arabika impor asal Brazil dengan rasa nutty cokelat klasik dunia, keasaman sangat rendah, dan body yang mantap.',
    story: 'Berasal dari perkebunan terbaik Minas Gerais Brazil, pilihan utama cafe specialty internasional.',
    basePrice: 92000,
    defaultWeight: '200g',
    variants: [
      { weightGrams: 200, weightLabel: '200g', price: 92000, inStock: true },
      { weightGrams: 500, weightLabel: '500g', price: 175000, inStock: true },
      { weightGrams: 1000, weightLabel: '1kg', price: 340000, inStock: true },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    acidity: 1,
    sweetness: 4,
    body: 5,
    brewingRecipe: {
      method: 'Espresso Machine',
      dose: '18.5g',
      water: '37g yield',
      ratio: '1:2',
      temp: '92°C',
      time: '28s',
      steps: ['Ekstraksi 37g espresso untuk Cafe Latte yang manis cokelat nutty tanpa asam.'],
    },
  },
];

export const FLAVOR_CATEGORIES = [
  { id: 'all', label: 'Semua Profil' },
  { id: 'Fruity', label: '🍓 Fruity & Berries' },
  { id: 'Floral', label: '🌸 Floral & Jasmine' },
  { id: 'Sweet', label: '🍯 Sweet & Honey' },
  { id: 'Chocolaty', label: '🍫 Chocolaty & Cocoa' },
  { id: 'Nutty', label: '🥜 Nutty & Almond' },
];

export const SERIES_CATEGORIES = [
  { id: 'all', label: 'Semua Seri' },
  { id: 'Ijen Series', label: 'Ijen Series' },
  { id: 'Enrekang Series', label: 'Enrekang Series' },
  { id: 'Sunda Series', label: 'Sunda Series' },
  { id: 'Java Exotic', label: 'Java Exotic' },
  { id: 'Argopuro Walida', label: 'Argopuro Walida' },
  { id: 'Grand Reserve', label: 'Grand Reserve' },
  { id: 'Robusta Espresso', label: 'Robusta Espresso' },
  { id: 'Arabica Espresso', label: 'Arabica Espresso' },
];

export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function getProductBySlug(slug: string): CoffeeProduct | undefined {
  return PRODUCTS.find((p) => p.slug === slug || p.id === slug);
}

export function getFeaturedProducts(): CoffeeProduct[] {
  return PRODUCTS.filter((p) => p.isFeatured);
}

export function getProductsByCategory(category: 'filter' | 'espresso' | 'reserve'): CoffeeProduct[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductsBySeries(series: CoffeeSeries): CoffeeProduct[] {
  return PRODUCTS.filter((p) => p.series === series);
}

